### ISSUE TITLE
Taloe Mixer MUX SN74CBT3253 needs I/O explanation

### ISSUE THREAD

**Issue by nickz12345** [cwill713/Software-Defined-Radio#15]
**Request**
Please clarify Taloe mixer operation and document sampling phase angles 0°, 90°, 180°, and 270°. 
See screenshot from your SDRrecV5 schematic:
 ![Taloe_SDRrecV5_sch_cwill713](https://user-images.githubusercontent.com/26151022/168161428-c5abebc0-645a-425c-a419-c3772e405531.PNG)

**Theory**
Quadrature sampling takes 0° and 90° outputs and amplifies them. See picture:
![GoodTaloe_Ex](https://user-images.githubusercontent.com/26151022/168159259-345cc0e7-f730-4f6a-b58a-7dae95a3b6fa.PNG)

Waveforms cos(x-180°) and cos(x-270°) are negative amplitude of waveforms cos(x-0°) and cos(x-90°) at the sampling frequency, so the amplified difference of the (cos(x-0°)-cos(x-180°)), and (cos(x-90°)-cos(x-270°)) effectively amplify 2cos(x-0°) and 2cos(x-90°). 

**Potential Issue**
Outputs coming out the the SN74CBT3253 Taloe mixer MUX are wired to the op-amps incorrectly if 1B1, 1B2, 1B3, and 1B4 are to be interpreted as 0°, 90°, 180°, and 270° respectively, and the same applies to the parallel duplicate outputs 2B1, 2B2, 2B3, and 2B4. This phase assumption might be valid for gray code clock inputs to the SN74CBT3253 MUX.  Under the assumption that your mixer outputs 1B1, 1B2, 1B3, and 1B4 are to be interpreted as 0°, 90°, 180°, and 270° respectively, then the top difference amplifier is amplifying the signal at (cos(x-0°)-cos(x-90°)) and (cos(x-180°)-cos(x-270°)). Under this assumption of 0°, 90°, 180°, and 270° respectively on the 1B1, 1B2, 1B3, and 1B4 outputs, the Taloe mixer will not quadrature sample properly. 

**References**
- [http://www.norcalqrp.org/files/Tayloe_mixer_x3a.pdf](url)

References:

**Comment by frohro** [comment]
I concur with Nick on this observation.  It is a good one.  I think he has an idea that might fix it in software that is worth trying.
