### ISSUE TITLE
SDA and SCL are 3.3V for the Si5351 and 5V for the Nano

### ISSUE THREAD

**Issue by frohro** [cwill713/Software-Defined-Radio#16]
Hi Guys,
Another issue you might have is that SDA and SCL on the I2C interface are 5V on the Nano and 3.3V on the Si5351.  It usually works, but not always.  You will need pull-ups to 3.3V for sure, but sometimes the Si5351 doesn't send a high enough signal to trigger the Nano.  You can fix this with a FET and a couple of resistors in between the two devices to level shift the signals.  Check to see you have the frequency you need.  You can skip Quisk and just open the serial monitor in the Arduino IDE and set the baud to 57600 and then type FREQ return, and then FREQ,14200000 to change the frequency to 14.2 MHz.  The latest code with the quadrature is in the muSDR branch on github of the IQ-SDR..
Rob

**Comment by cwill713** [comment]
When checking the signal integrity we found that the Si5351 was sending a strong enough signal to trigger our Arduino Nano.
